USE ADMIN_USERS
GO

IF OBJECT_ID('[USERS]') IS NOT NULL
	DROP TABLE [USERS]
GO

CREATE TABLE [USERS](
id BIGINT NOT NULL PRIMARY KEY IDENTITY,
documentType_id INT NOT NULL,
documentNumber BIGINT NOT NULL,
[name] VARCHAR(30) NOT NULL,
[surname] VARCHAR(30) NOT NULL,
[login] VARCHAR(20) NOT NULL,
[password] VARCHAR(20) NOT NULL,
email VARCHAR(30) NOT NULL,
createBy BIGINT NOT NULL,
dateCreate DATE NOT NULL,
modifyBy BIGINT NULL,
dateModify DATE NULL,
active BIT NOT NULL,
profile_id INT NOT NULL,
FOREIGN KEY(documentType_id) REFERENCES DOCUMENTTYPES(id),
FOREIGN KEY(profile_id) REFERENCES PROFILES(id)
)
GO
