USE ADMIN_USERS
GO

IF OBJECT_ID('LOG_USERS') IS NOT NULL
	DROP TABLE LOG_USERS
GO

CREATE TABLE LOG_USERS(
id BIGINT NOT NULL PRIMARY KEY IDENTITY,
dateCreate DATETIME NOT NULL,
[user_id] BIGINT NOT NULL,
modifyBy_id BIGINT NOT NULL,
detail VARCHAR(255) NOT NULL
)
GO
