USE ADMIN_USERS
GO

IF OBJECT_ID('DOCUMENTTYPES') IS NOT NULL
	DROP TABLE DOCUMENTTYPES
GO

CREATE TABLE DOCUMENTTYPES(
id INT PRIMARY KEY NOT NULL,
documentType VARCHAR(30) NOT NULL
)
GO

INSERT INTO DOCUMENTTYPES VALUES (1,'Cedula Ciudadania'),(2,'Cedula Extrangeria')
